// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RpsArena.Match.Infrastructure.Persistence;

#nullable disable

namespace RpsArena.Match.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MatchDbContext))]
    [Migration("20260708051228_AddMatches")]
    partial class AddMatches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RpsArena.Match.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<Guid>("PlayerOneId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_one_id");

                    b.Property<int>("PlayerOneScore")
                        .HasColumnType("integer")
                        .HasColumnName("player_one_score");

                    b.Property<Guid>("PlayerTwoId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_two_id");

                    b.Property<int>("PlayerTwoScore")
                        .HasColumnType("integer")
                        .HasColumnName("player_two_score");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_matches_idempotency_key");

                    b.HasIndex("PlayedAt")
                        .HasDatabaseName("ix_matches_played_at");

                    b.HasIndex("PlayerOneId")
                        .HasDatabaseName("ix_matches_player_one_id");

                    b.HasIndex("PlayerTwoId")
                        .HasDatabaseName("ix_matches_player_two_id");

                    b.ToTable("matches", null, t =>
                        {
                            t.HasCheckConstraint("ck_matches_no_self_play", "player_one_id <> player_two_id");

                            t.HasCheckConstraint("ck_matches_scores_non_negative", "player_one_score >= 0 AND player_two_score >= 0");
                        });
                });

            modelBuilder.Entity("RpsArena.Match.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_players_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_players_username");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("RpsArena.Match.Domain.Entities.Match", b =>
                {
                    b.HasOne("RpsArena.Match.Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerOneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_players_player_one_id");

                    b.HasOne("RpsArena.Match.Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerTwoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_players_player_two_id");
                });
#pragma warning restore 612, 618
        }
    }
}
